services:
  postgres:
    image: postgres:17-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data_QLCC_4Bros_BE
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d data_QLCC_4Bros_BE']
      interval: 5s
      timeout: 5s
      retries: 10

  nest:
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  postgres_data:
