services:
  postgres:
    image: postgres:17-bookworm
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data_QLCC_4Bros_BE
